---   
- name: Set kern.maxfiles
  sysctl:
    name: kern.maxfiles
    value: 200000
    state: present
    reload: yes
- name: Set kern.maxfilesperproc
  sysctl:
    name: kern.maxfilesperproc
    value: 200000
    state: present
    reload: yes
- name: Create directory for data
  file:
    path: "/mnt/block-volume/{{ node_user_name }}/data"
    state: directory
    mode: '0755'
- name: Change ownership of block volume
  become: yes
  file:
    path: "/mnt/block-volume/{{ node_user_name }}"
    owner: "{{ node_user_name }}"
    group: "{{ node_user_name }}"
    recurse: yes

- name: List contents of the destination folder
  find:
    paths: "{{ dest_folder }}"
    file_type: directory
    depth: 1
  register: folder_contents
- name: Set extracted folder name
  set_fact:
    extracted_folder_name: "{{ item.path | basename }}"
  with_items: "{{ folder_contents.files }}"

- name: Create systemd service file for Nimbus
  template:
    src: nimbus_service.j2
    dest: /etc/systemd/system/nimbus.service
    mode: '0644'
  vars:
    nimbus_path: "{{ dest_folder }}"
    nimbus_folder_name: "{{ extracted_folder_name }}"
- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Enable and start Nimbus service
  systemd:
    name: nimbus
    enabled: yes
    state: started