---   
  - name: Create systemd service file for Nimbus
    template:
      src: nimbus_service.j2
      dest: /etc/systemd/system/nimbus.service
      mode: '0644'
    vars:
      nimbus_path: "{{ dest_folder }}"

  - name: Reload systemd daemon
    command: systemctl daemon-reload

  - name: Enable and start Nimbus service
    systemd:
      name: nimbus
      enabled: yes
      state: started