---
  - name: Generate JWT hex key
    command: openssl rand -hex 32 > /tmp/jwt.hex
    args:
      creates: /tmp/jwt.hex
  - name: Copy JWT to control node
    fetch:
      src: /tmp/jwt.hex
      dest: files/jwt.hex
      flat: yes
