---
- name: Deploy node exporter and system setup on both machines
  hosts: all
  become: true
  roles:
    - role: node_exporter
    - role: system_setup

- name: Generate JWT token
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run generate_jwt role to generate and fetch the JWT token
      include_role:
        name: generate_jwt

- name: Distribute JWT to both machines
  hosts: all
  become: true
  tasks:
    - name: Ensure the config directory exists
      file:
        path: /mnt/block-volume/ethereum/config
        state: directory
        mode: '0755'

    - name: Copy JWT to target machine
      copy:
        src: files/jwt.hex
        dest: /mnt/block-volume/ethereum/config/jwt.hex

- name: Configure Nimbus on machine A
  hosts: machine_a
  become: true
  roles:
    - nimbus

- name: Configure Nethermind on machine B
  hosts: machine_b
  become: true
  roles:
    - nethermind

