---
- name: Change system limits for nethermind
  ansible.builtin.copy:
    dest: /etc/security/limits.d/nethermind.conf
    content: |
      nethermind soft nofile 100000
      nethermind hard nofile 100000
- name: Create directory for data
  file:
    path: "/mnt/block-volume/{{ node_user_name }}/data"
    state: directory
    mode: '0755'
- name: Change ownership of block volume
  become: yes
  file:
    path: "/mnt/block-volume/{{ node_user_name }}"
    owner: "{{ node_user_name }}"
    group: "{{ node_user_name }}"
    recurse: yes
- name: Create systemd service file for Nethermind
  template:
    src: nethermind_service.j2
    dest: /etc/systemd/system/nethermind.service
    mode: '0644'
  vars:
    nethermind_path: "/mnt/block-volume/{{ node_user_name }}/.bin/{{ release_info.json.tag_name }}"
- name: Reload systemd daemon
  command: systemctl daemon-reload
- name: Enable and start Nethermind service
  systemd:
    name: nethermind
    enabled: yes
    state: started