---
- name: Create directory for data
  file:
    path: "/mnt/block-volume/ethereum/data"
    state: directory
    mode: '0755'
- name: Create systemd service file for Nethermind
  template:
    src: nethermind_service.j2
    dest: /etc/systemd/system/nethermind.service
    mode: '0644'
  vars:
    nethermind_path: "/mnt/block-volume/ethereum/.bin/nethermind/{{ release_info.json.tag_name }}"
- name: Reload systemd daemon
  command: systemctl daemon-reload
- name: Enable and start Nethermind service
  systemd:
    name: nethermind
    enabled: yes
    state: started